export const dataPulsa = [
  {
    kode_produk: 'AX10',
    kode_provider: 'AXIS',
    dsc: 'PULSA AXIS REGULER 10.000',
    short_dsc: '10.000',
    category: '#PULSA',
    price: '10150',
    outlet_price: '13000',
    min_qty: '',
    max_qty: '',
    admin: '0',
    img_url: 'https://homepages.cae.wisc.edu/~ece533/images/airplane.png',
    is_active: '1',
    is_faktur: '1',
    opr_name: 'PULSA REGULER',
    stock_type: '',
    product_type: '',
  },
  {
    kode_produk: 'AX12',
    kode_provider: 'AXIS',
    dsc: 'PULSA AXIX REGULER 12.000',
    short_dsc: '',
    category: '#PULSA',
    price: '12150',
    outlet_price: '12150',
    min_qty: '',
    max_qty: '',
    admin: '0',
    img_url: 'https://homepages.cae.wisc.edu/~ece533/images/airplane.png',
    is_active: '1',
    is_faktur: '1',
    opr_name: '',
    stock_type: '',
    product_type: '',
  },
  {
    kode_produk: 'AX25',
    kode_provider: 'AXIS',
    dsc: 'PULSA AXIS REGULER 25.000',
    short_dsc: '25.000',
    category: '#PULSA',
    price: '25150',
    outlet_price: '25150',
    min_qty: '',
    max_qty: '',
    admin: '0',
    img_url: 'https://homepages.cae.wisc.edu/~ece533/images/airplane.png',
    is_active: '1',
    is_faktur: '1',
    opr_name: 'PULSA REGULER',
    stock_type: '',
    product_type: '',
  },
  {
    kode_produk: 'AX50',
    kode_provider: 'AXIS',
    dsc: 'PULSA AXIS REGULER 50.000',
    short_dsc: '50.000',
    category: '#PULSA',
    price: '50150',
    outlet_price: '50150',
    min_qty: '',
    max_qty: '',
    admin: '0',
    img_url: 'https://homepages.cae.wisc.edu/~ece533/images/airplane.png',
    is_active: '1',
    is_faktur: '1',
    opr_name: 'PULSA REGULER',
    stock_type: '',
    product_type: '',
  },
  {
    kode_produk: 'AX100',
    kode_provider: 'AXIS',
    dsc: 'PULSA AXIS REGULER 100.000',
    short_dsc: '100.000',
    category: '#PULSA',
    price: '100150',
    outlet_price: '100150',
    min_qty: '',
    max_qty: '',
    admin: '0',
    img_url: 'https://homepages.cae.wisc.edu/~ece533/images/airplane.png',
    is_active: '1',
    is_faktur: '1',
    opr_name: 'PULSA REGULER',
    stock_type: '',
    product_type: '',
  },
  {
    kode_produk: 'AX200',
    kode_provider: 'AXIS',
    dsc: 'PULSA AXIS REGULER 200.000',
    short_dsc: '200.000',
    category: '#PULSA',
    price: '200150',
    outlet_price: '200150',
    min_qty: '',
    max_qty: '',
    admin: '0',
    img_url: 'https://homepages.cae.wisc.edu/~ece533/images/airplane.png',
    is_active: '1',
    is_faktur: '1',
    opr_name: 'PULSA REGULER',
    stock_type: '',
    product_type: '',
  },
  {
    kode_produk: 'PAYDIGIPOS1',
    kode_provider: 'AXIS',
    dsc: 'PULSA AXIS REGULER 5.000',
    short_dsc: '5.000',
    category: '#PULSA',
    price: '200',
    outlet_price: '200',
    min_qty: '',
    max_qty: '',
    admin: '0',
    img_url: 'https://homepages.cae.wisc.edu/~ece533/images/airplane.png',
    is_active: '1',
    is_faktur: '1',
    opr_name: 'PULSA REGULER',
    stock_type: '',
    product_type: '',
  },
];
